import type { Metadata } from "next";
import { Inria_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const inriaSans = Inria_Sans({
  variable: "--font-inria-sans",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});
export const metadata: Metadata = {
  title: "BookQuestion | Powered by AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inriaSans.variable} antialiased overflow-x-hidden`}>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
        <Footer />
      </body>
    </html>
  );
}
